#
# Author:linrol
#

version: '2'

services:
  coolq:
    image: richardchien/cqhttp
    restart: always
    container_name: coolq-${COOL_TYPE}
    volumes:
      - /root/web/app/coolq/air:/home/user/coolq
    environment:
      - VNC_PASSWD=19941208
      - COOLQ_URL=https://dlsec.cqp.me/cq${COOL_TYPE}-tuling
      - COOLQ_ACCOUNT=${COOL_QQ}
      - CQHTTP_USE_HTTP=false
      - CQHTTP_USE_WS_REVERSE=true
      - CQHTTP_WS_REVERSE_URL=ws://www.alinkeji.com:${WS_PORT}/ws/universal/
      - CQHTTP_WS_REVERSE_UNIVERSAL_CLIENT=true
    ports:
      - ${VNC_PORT}:9000
  spring-coolq:
    image: spring-coolq
    restart: always
    container_name: spring-coolq
    volumes:
      - /root/web/log/spring-coolq/:/logs
    environment:
      - JAVA_OPTS=-Xmx2048m -Xms1024m
    expose:
      - ${WS_PORT}
    ports:
      - ${WS_PORT}:8081
    depends_on:
      - coolq


