#
# Author:linrol
#

version: '2'

services:
  redis:
    image: docker.io/redis
    container_name: redis
    command: redis-server --requirepass linrol_redis --appendonly yes
    expose:
      - 6379
    ports:
      - 6379:6379
    restart: always
    volumes:
      - /root/web/app/redis/data:/data
  coolq-pro:
    image: richardchien/cqhttp:latest
    restart: always
    container_name: coolq-pro
    volumes:
      - /root/web/app/coolq/coolq-pro:/home/user/coolq
    environment:
      - VNC_PASSWD=19941208
      - COOLQ_URL=https://dlsec.cqp.me/cqp-tuling
      - COOLQ_ACCOUNT=${COOL_QQ}
      - FORCE_ENV=true
      - CQHTTP_USE_HTTP=true
      - CQHTTP_USE_WS_REVERSE=true
      - CQHTTP_WS_REVERSE_URL=ws://${DEPLOY_HOST}:${WS_PORT}/ws/universal/
      - CQHTTP_WS_REVERSE_UNIVERSAL_CLIENT=true
      - CQHTTP_LOG_LEVEL=debug
      - CQHTTP_SHOW_LOG_CONSOLE=true
      - CQHTTP_WS_REVERSE_RECONNECT_INTERVAL=2000
      - CQHTTP_WS_REVERSE_RECONNECT_ON_CODE_1000=true
    ports:
      - 8000:9000
      - 5700:5700
  coolq-pro-slave:
    image: richardchien/cqhttp:latest
    restart: always
    container_name: coolq-pro-slave
    volumes:
      - /root/web/app/coolq/coolq-pro-slave:/home/user/coolq
    environment:
      - VNC_PASSWD=19941208
      - COOLQ_URL=https://dlsec.cqp.me/cqp-tuling
      - COOLQ_ACCOUNT=${COOL_QQ}
      - FORCE_ENV=true
      - CQHTTP_USE_HTTP=true
      - CQHTTP_USE_WS_REVERSE=true
      - CQHTTP_WS_REVERSE_URL=ws://${DEPLOY_HOST}:${WS_PORT}/ws/universal/
      - CQHTTP_WS_REVERSE_UNIVERSAL_CLIENT=true
      - CQHTTP_LOG_LEVEL=debug
      - CQHTTP_SHOW_LOG_CONSOLE=true
      - CQHTTP_WS_REVERSE_RECONNECT_INTERVAL=2000
      - CQHTTP_WS_REVERSE_RECONNECT_ON_CODE_1000=true
    ports:
      - 8001:9000
  coolq-air:
    image: richardchien/cqhttp:latest
    restart: always
    container_name: coolq-air
    volumes:
      - /root/web/app/coolq/coolq-air:/home/user/coolq
    environment:
      - VNC_PASSWD=19941208
      - COOLQ_URL=http://dlsec.cqp.me/cqa-tuling
      - COOLQ_ACCOUNT=${COOL_QQ}
      - FORCE_ENV=true
      - CQHTTP_USE_HTTP=true
      - CQHTTP_USE_WS_REVERSE=true
      - CQHTTP_WS_REVERSE_URL=ws://${DEPLOY_HOST}:${WS_PORT}/ws/universal/
      - CQHTTP_WS_REVERSE_UNIVERSAL_CLIENT=true
      - CQHTTP_LOG_LEVEL=debug
      - CQHTTP_SHOW_LOG_CONSOLE=true
      - CQHTTP_WS_REVERSE_RECONNECT_INTERVAL=2000
      - CQHTTP_WS_REVERSE_RECONNECT_ON_CODE_1000=true
    ports:
      - 8002:9000
  coolq-air-slave:
    image: richardchien/cqhttp:latest
    restart: always
    container_name: coolq-air-slave
    volumes:
      - /root/web/app/coolq/coolq-air-slave:/home/user/coolq
    environment:
      - VNC_PASSWD=19941208
      - COOLQ_URL=http://dlsec.cqp.me/cqa-tuling
      - COOLQ_ACCOUNT=${COOL_QQ}
      - FORCE_ENV=true
      - CQHTTP_USE_HTTP=true
      - CQHTTP_USE_WS_REVERSE=true
      - CQHTTP_WS_REVERSE_URL=ws://${DEPLOY_HOST}:${WS_PORT}/ws/universal/
      - CQHTTP_WS_REVERSE_UNIVERSAL_CLIENT=true
      - CQHTTP_LOG_LEVEL=debug
      - CQHTTP_SHOW_LOG_CONSOLE=true
      - CQHTTP_WS_REVERSE_RECONNECT_INTERVAL=2000
      - CQHTTP_WS_REVERSE_RECONNECT_ON_CODE_1000=true
    ports:
      - 8003:9000