#
# Author:linrol
#

version: '2'

services:
  spring-coolq:
    image: spring-coolq
    restart: always
    container_name: spring-coolq
    volumes:
      - /root/web/log/spring-coolq/:/logs
    environment:
      - JAVA_OPTS=-Xmx2048m -Xms1024m
    expose:
      - 8081
    ports:
      - 8082:8081