#
# Author:linrol
#

version: '2'

services:
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --requirepass linrol_redis
    expose:
      - 6379
    ports:
      - 6379:6379
    restart: always
    ports:
      - 6379:6379
  coolq-pro:
    image: richardchien/cqhttp
    restart: always
    container_name: coolq-pro
    volumes:
      - /root/web/app/coolq/coolq-pro:/home/user/coolq
    environment:
      - VNC_PASSWD=19941208
      - COOLQ_URL=https://dlsec.cqp.me/cqp-tuling
      - COOLQ_ACCOUNT=${COOL_QQ}
      - CQHTTP_USE_HTTP=false
      - CQHTTP_USE_WS_REVERSE=true
      - CQHTTP_WS_REVERSE_URL=ws://${DEPLOY_HOST}:${WS_PORT}/ws/universal/
      - CQHTTP_WS_REVERSE_UNIVERSAL_CLIENT=true
    ports:
      - ${VNC_PORT}:9000
  coolq-pro-slave:
    image: richardchien/cqhttp
    restart: always
    container_name: coolq-pro-slave
    volumes:
      - /root/web/app/coolq/coolq-pro-slave:/home/user/coolq
    environment:
      - VNC_PASSWD=19941208
      - COOLQ_URL=https://dlsec.cqp.me/cqp-tuling
      - COOLQ_ACCOUNT=${COOL_QQ}
      - CQHTTP_USE_HTTP=false
      - CQHTTP_USE_WS_REVERSE=true
      - CQHTTP_WS_REVERSE_URL=ws://${DEPLOY_HOST}:${WS_PORT}/ws/universal/
      - CQHTTP_WS_REVERSE_UNIVERSAL_CLIENT=true
    ports:
      - ${VNC_PORT}:9000
  coolq-air:
    image: richardchien/cqhttp
    restart: always
    container_name: coolq-air
    volumes:
      - /root/web/app/coolq/coolq-air:/home/user/coolq
    environment:
      - VNC_PASSWD=19941208
      - COOLQ_URL=http://dlsec.cqp.me/cqa-tuling
      - COOLQ_ACCOUNT=${COOL_QQ}
      - CQHTTP_USE_HTTP=false
      - CQHTTP_USE_WS_REVERSE=true
      - CQHTTP_WS_REVERSE_URL=ws://${DEPLOY_HOST}:${WS_PORT}/ws/universal/
      - CQHTTP_WS_REVERSE_UNIVERSAL_CLIENT=true
    ports:
      - ${VNC_PORT}:9000
  coolq-air-slave:
    image: richardchien/cqhttp
    restart: always
    container_name: coolq-air-slave
    volumes:
      - /root/web/app/coolq/coolq-air-slave:/home/user/coolq
    environment:
      - VNC_PASSWD=19941208
      - COOLQ_URL=http://dlsec.cqp.me/cqa-tuling
      - COOLQ_ACCOUNT=${COOL_QQ}
      - CQHTTP_USE_HTTP=false
      - CQHTTP_USE_WS_REVERSE=true
      - CQHTTP_WS_REVERSE_URL=ws://${DEPLOY_HOST}:${WS_PORT}/ws/universal/
      - CQHTTP_WS_REVERSE_UNIVERSAL_CLIENT=true
    ports:
      - ${VNC_PORT}:9000  


